title: PrivateAI $PGPT Ecosystem Roadmap
description: Comprehensive documentation of AI-powered trading and research intelligence tools
remote_theme: just-the-docs/just-the-docs

# Site settings
baseurl: "/PrivateAI-PGPT-Roadmap"
url: "https://privateai-com.github.io"

# Just the Docs theme settings
color_scheme: light
search_enabled: true
heading_anchors: true

# Logo
logo: "/logo-pgpt/logo.png"

# Footer content
footer_content: "© 2025 PrivateAI. All rights reserved."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Navigation
nav_links:
  - title: Overview
    url: /
  - title: The Thing
    url: /the-thing
  - title: Trading
    url: /trading-platform
  - title: Research
    url: /research-ai
  - title: Token Utility
    url: /token-utility

# Social
github_username: privateai-com
twitter_username: PrivateAI_PGPT

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO defaults
author: PrivateAI
twitter:
  username: PrivateAI_PGPT
  card: summary_large_image
logo: /assets/images/logo.png
social:
  name: PrivateAI
  links:
    - https://twitter.com/PrivateAI_PGPT
    - https://github.com/privateai-com
